import { IconMoon } from './components/Icons'
import './globals.css'
import { Nunito_Sans } from 'next/font/google'

const Nunito = Nunito_Sans({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout({
  children
}: {
  children: React.ReactNode
}) {
  return (
    <html lang='en'>
      <body
        className={`${Nunito.className} bg-dark-mode-bg text-dark-mode-text`}
      >
        <header className='flex w-full justify-between px-5 py-7 bg-dark-mode-element'>
          <h1 className='font-bold'>Where in the world?</h1>

          <div className='flex items-center gap-2'>
            <IconMoon />
            <p className='text-sm'>Dark Mode</p>
          </div>
        </header>
        {children}
      </body>
    </html>
  )
}
