import Header from '@/components/Header'
import './globals.css'
import { Nunito_Sans } from 'next/font/google'

const Nunito = Nunito_Sans({
  subsets: ['latin'],
  variable: '--font-nunito_sans'
})

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout({
  children
}: {
  children: React.ReactNode
}) {
  return (
    <html lang='en'>
      <body
        className={`${Nunito.className} bg-dark-mode-bg text-dark-mode-text`}
      >
        <Header />
        {children}
      </body>
    </html>
  )
}
