import { IconMoon } from '../components/Icons'
import './globals.css'
import { Nunito_Sans } from 'next/font/google'

const Nunito = Nunito_Sans({
  subsets: ['latin'],
  variable: '--font-nunito_sans'
})

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout({
  children
}: {
  children: React.ReactNode
}) {
  return (
    <html lang='en'>
      <body
        className={`${Nunito.className} bg-dark-mode-bg text-dark-mode-text`}
      >
        <header className='w-full  px-5 py-7 bg-dark-mode-element'>
          <div className='flex justify-between w-full max-w-[1300px] mx-auto'>
            <h1 className='font-bold'>Where in the world?</h1>

            <div className='flex items-center gap-2'>
              <IconMoon />
              <p className='text-sm'>Dark Mode</p>
            </div>
          </div>
        </header>
        {children}
      </body>
    </html>
  )
}
